version: '3.7'

services:
  server:
    image: urbinek/auto-nicehash-withdraw:latest

    networks:
      - overlay

    ports:
      - "8321:80/tcp"

    volumes:
      - type: volume
        source: auto-nicehash-withdraw_db
        target: /db

      - type: bind
        read_only: true
        source: /etc/localtime
        target: /etc/localtime

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

    stdin_open: true
    tty: true

networks:
  overlay:

volumes:
  bc_fee_monitor_db:
    external: true
